# BUILD
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /source
COPY . .
RUN dotnet restore "./Loppuprojekti.csproj"
RUN dotnet publish "./Loppuprojekti.csproj" -c release -o /app --no-restore

# SERVE
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build /app ./

ENTRYPOINT ["dotnet", "Loppuprojekti.dll"]